// This file is auto-generated by @hey-api/openapi-ts

import { type Client, formDataBodySerializer, type Options as Options2, type TDataShape } from './client';
import { client } from './client.gen';
import type { ChatWithPdfApiChatPdfNoteIdPostData, ChatWithPdfApiChatPdfNoteIdPostErrors, ChatWithPdfApiChatPdfNoteIdPostResponses, CreateNoteApiNotesPostData, CreateNoteApiNotesPostErrors, CreateNoteApiNotesPostResponses, DeleteNoteApiNotesNoteIdDeleteData, DeleteNoteApiNotesNoteIdDeleteErrors, DeleteNoteApiNotesNoteIdDeleteResponses, GetSummaryApiSummaryGetData, GetSummaryApiSummaryGetResponses, GetTimelineApiTimelineGetData, GetTimelineApiTimelineGetErrors, GetTimelineApiTimelineGetResponses, HealthCheckHealthGetData, HealthCheckHealthGetResponses, RefreshSummaryApiSummaryRefreshPostData, RefreshSummaryApiSummaryRefreshPostResponses, SearchNotesApiSearchGetData, SearchNotesApiSearchGetErrors, SearchNotesApiSearchGetResponses, UploadFileApiUploadPostData, UploadFileApiUploadPostErrors, UploadFileApiUploadPostResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Create Note
 *
 * Create a new note.
 * Triggers vectorization automatically.
 */
export const createNoteApiNotesPost = <ThrowOnError extends boolean = false>(options: Options<CreateNoteApiNotesPostData, ThrowOnError>) => (options.client ?? client).post<CreateNoteApiNotesPostResponses, CreateNoteApiNotesPostErrors, ThrowOnError>({
    url: '/api/notes',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get Timeline
 *
 * Get recent notes (timeline).
 */
export const getTimelineApiTimelineGet = <ThrowOnError extends boolean = false>(options?: Options<GetTimelineApiTimelineGetData, ThrowOnError>) => (options?.client ?? client).get<GetTimelineApiTimelineGetResponses, GetTimelineApiTimelineGetErrors, ThrowOnError>({ url: '/api/timeline', ...options });

/**
 * Search Notes
 *
 * Semantic search for notes.
 */
export const searchNotesApiSearchGet = <ThrowOnError extends boolean = false>(options: Options<SearchNotesApiSearchGetData, ThrowOnError>) => (options.client ?? client).get<SearchNotesApiSearchGetResponses, SearchNotesApiSearchGetErrors, ThrowOnError>({ url: '/api/search', ...options });

/**
 * Delete Note
 *
 * Delete a note permanently.
 */
export const deleteNoteApiNotesNoteIdDelete = <ThrowOnError extends boolean = false>(options: Options<DeleteNoteApiNotesNoteIdDeleteData, ThrowOnError>) => (options.client ?? client).delete<DeleteNoteApiNotesNoteIdDeleteResponses, DeleteNoteApiNotesNoteIdDeleteErrors, ThrowOnError>({ url: '/api/notes/{note_id}', ...options });

/**
 * Get Summary
 *
 * Get the latest rolling summary.
 * If no summary exists, attempts to generate one.
 */
export const getSummaryApiSummaryGet = <ThrowOnError extends boolean = false>(options?: Options<GetSummaryApiSummaryGetData, ThrowOnError>) => (options?.client ?? client).get<GetSummaryApiSummaryGetResponses, unknown, ThrowOnError>({ url: '/api/summary', ...options });

/**
 * Refresh Summary
 *
 * Force regenerate the rolling summary based on latest notes.
 */
export const refreshSummaryApiSummaryRefreshPost = <ThrowOnError extends boolean = false>(options?: Options<RefreshSummaryApiSummaryRefreshPostData, ThrowOnError>) => (options?.client ?? client).post<RefreshSummaryApiSummaryRefreshPostResponses, unknown, ThrowOnError>({ url: '/api/summary/refresh', ...options });

/**
 * Upload File
 *
 * Upload a file (Image/Audio/PDF).
 * - Images: Caption generated.
 * - Audio: Transcribed.
 * - PDF: Text extracted, chunked, and ingested as Notes (searchable).
 */
export const uploadFileApiUploadPost = <ThrowOnError extends boolean = false>(options: Options<UploadFileApiUploadPostData, ThrowOnError>) => (options.client ?? client).post<UploadFileApiUploadPostResponses, UploadFileApiUploadPostErrors, ThrowOnError>({
    ...formDataBodySerializer,
    url: '/api/upload',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});

/**
 * Chat With Pdf
 *
 * Dual-Agent Chat with a specific PDF Memory.
 * 1. Retrieve Context (Scoped RAG).
 * 2. Messenger generates answer.
 * 3. Auditor verifies answer.
 */
export const chatWithPdfApiChatPdfNoteIdPost = <ThrowOnError extends boolean = false>(options: Options<ChatWithPdfApiChatPdfNoteIdPostData, ThrowOnError>) => (options.client ?? client).post<ChatWithPdfApiChatPdfNoteIdPostResponses, ChatWithPdfApiChatPdfNoteIdPostErrors, ThrowOnError>({
    url: '/api/chat/pdf/{note_id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Health Check
 */
export const healthCheckHealthGet = <ThrowOnError extends boolean = false>(options?: Options<HealthCheckHealthGetData, ThrowOnError>) => (options?.client ?? client).get<HealthCheckHealthGetResponses, unknown, ThrowOnError>({ url: '/health', ...options });
