// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * Body_upload_file_api_upload_post
 */
export type BodyUploadFileApiUploadPost = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * ChatRequest
 */
export type ChatRequest = {
    /**
     * Query
     */
    query: string;
};

/**
 * ChatResponse
 */
export type ChatResponse = {
    /**
     * Answer
     */
    answer: string;
    /**
     * Verified
     */
    verified: boolean;
    /**
     * Correction
     */
    correction?: string | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * MediaType
 */
export type MediaType = 'text' | 'voice' | 'image' | 'link' | 'pdf';

/**
 * NoteCreate
 */
export type NoteCreate = {
    /**
     * Content
     */
    content: string;
    media_type?: MediaType;
    /**
     * Tags
     */
    tags?: Array<string>;
    /**
     * File Path
     */
    file_path?: string | null;
    /**
     * Parent Id
     */
    parent_id?: number | null;
    /**
     * Is Hidden
     */
    is_hidden?: boolean;
};

/**
 * NoteResponse
 */
export type NoteResponse = {
    /**
     * Content
     */
    content: string;
    media_type?: MediaType;
    /**
     * Tags
     */
    tags?: Array<string>;
    /**
     * Id
     */
    id: number;
    /**
     * Summary
     */
    summary?: string | null;
    /**
     * File Path
     */
    file_path?: string | null;
    /**
     * Parent Id
     */
    parent_id?: number | null;
    /**
     * Category
     */
    category?: string | null;
    /**
     * Event At
     */
    event_at?: string | null;
    /**
     * Event Duration
     */
    event_duration?: number;
    /**
     * Is Hidden
     */
    is_hidden?: boolean;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Is Active
     */
    is_active: boolean;
    /**
     * Is Processing
     */
    is_processing?: boolean;
};

/**
 * SearchResult
 */
export type SearchResult = {
    note: NoteResponse;
    /**
     * Distance
     */
    distance: number;
};

/**
 * SummaryResponse
 */
export type SummaryResponse = {
    /**
     * Id
     */
    id: number;
    /**
     * Date Bucket
     */
    date_bucket: string;
    /**
     * Summary Text
     */
    summary_text: string;
    /**
     * Linked Note Ids
     */
    linked_note_ids: Array<number>;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Tasks
     */
    tasks?: Array<TaskItem>;
};

/**
 * TaskItem
 */
export type TaskItem = {
    /**
     * Task
     */
    task: string;
    /**
     * Priority
     */
    priority: string;
    /**
     * Timeline
     */
    timeline: string;
};

/**
 * UploadResponse
 */
export type UploadResponse = {
    /**
     * File Path
     */
    file_path: string;
    /**
     * Media Type
     */
    media_type: string;
    /**
     * Extracted Content
     */
    extracted_content: string;
    /**
     * Chunks Created
     */
    chunks_created?: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type CreateNoteApiNotesPostData = {
    body: NoteCreate;
    path?: never;
    query?: never;
    url: '/api/notes';
};

export type CreateNoteApiNotesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateNoteApiNotesPostError = CreateNoteApiNotesPostErrors[keyof CreateNoteApiNotesPostErrors];

export type CreateNoteApiNotesPostResponses = {
    /**
     * Successful Response
     */
    200: NoteResponse;
};

export type CreateNoteApiNotesPostResponse = CreateNoteApiNotesPostResponses[keyof CreateNoteApiNotesPostResponses];

export type GetTimelineApiTimelineGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/timeline';
};

export type GetTimelineApiTimelineGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetTimelineApiTimelineGetError = GetTimelineApiTimelineGetErrors[keyof GetTimelineApiTimelineGetErrors];

export type GetTimelineApiTimelineGetResponses = {
    /**
     * Response Get Timeline Api Timeline Get
     *
     * Successful Response
     */
    200: Array<NoteResponse>;
};

export type GetTimelineApiTimelineGetResponse = GetTimelineApiTimelineGetResponses[keyof GetTimelineApiTimelineGetResponses];

export type SearchNotesApiSearchGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Q
         */
        q: string;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/search';
};

export type SearchNotesApiSearchGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SearchNotesApiSearchGetError = SearchNotesApiSearchGetErrors[keyof SearchNotesApiSearchGetErrors];

export type SearchNotesApiSearchGetResponses = {
    /**
     * Response Search Notes Api Search Get
     *
     * Successful Response
     */
    200: Array<SearchResult>;
};

export type SearchNotesApiSearchGetResponse = SearchNotesApiSearchGetResponses[keyof SearchNotesApiSearchGetResponses];

export type DeleteNoteApiNotesNoteIdDeleteData = {
    body?: never;
    path: {
        /**
         * Note Id
         */
        note_id: number;
    };
    query?: never;
    url: '/api/notes/{note_id}';
};

export type DeleteNoteApiNotesNoteIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteNoteApiNotesNoteIdDeleteError = DeleteNoteApiNotesNoteIdDeleteErrors[keyof DeleteNoteApiNotesNoteIdDeleteErrors];

export type DeleteNoteApiNotesNoteIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetSummaryApiSummaryGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/summary';
};

export type GetSummaryApiSummaryGetResponses = {
    /**
     * Successful Response
     */
    200: SummaryResponse;
};

export type GetSummaryApiSummaryGetResponse = GetSummaryApiSummaryGetResponses[keyof GetSummaryApiSummaryGetResponses];

export type RefreshSummaryApiSummaryRefreshPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/summary/refresh';
};

export type RefreshSummaryApiSummaryRefreshPostResponses = {
    /**
     * Successful Response
     */
    200: SummaryResponse;
};

export type RefreshSummaryApiSummaryRefreshPostResponse = RefreshSummaryApiSummaryRefreshPostResponses[keyof RefreshSummaryApiSummaryRefreshPostResponses];

export type UploadFileApiUploadPostData = {
    body: BodyUploadFileApiUploadPost;
    path?: never;
    query?: never;
    url: '/api/upload';
};

export type UploadFileApiUploadPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadFileApiUploadPostError = UploadFileApiUploadPostErrors[keyof UploadFileApiUploadPostErrors];

export type UploadFileApiUploadPostResponses = {
    /**
     * Successful Response
     */
    200: UploadResponse;
};

export type UploadFileApiUploadPostResponse = UploadFileApiUploadPostResponses[keyof UploadFileApiUploadPostResponses];

export type ChatWithPdfApiChatPdfNoteIdPostData = {
    body: ChatRequest;
    path: {
        /**
         * Note Id
         */
        note_id: number;
    };
    query?: never;
    url: '/api/chat/pdf/{note_id}';
};

export type ChatWithPdfApiChatPdfNoteIdPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ChatWithPdfApiChatPdfNoteIdPostError = ChatWithPdfApiChatPdfNoteIdPostErrors[keyof ChatWithPdfApiChatPdfNoteIdPostErrors];

export type ChatWithPdfApiChatPdfNoteIdPostResponses = {
    /**
     * Successful Response
     */
    200: ChatResponse;
};

export type ChatWithPdfApiChatPdfNoteIdPostResponse = ChatWithPdfApiChatPdfNoteIdPostResponses[keyof ChatWithPdfApiChatPdfNoteIdPostResponses];

export type HealthCheckHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthCheckHealthGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
